name: Build Wheels
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: 'false'

      - name: Build wheel
        uses: pypa/cibuildwheel@v4.2.1

      - uses: actions/upload-artifact@v4
        with:
          name: 'paul-wheels-${{ matrix.os }}-${{ strategy.job-index }}'
          path: ./wheelhouse/*.whl
